package:
  name: imagehash
  version: "3.1"

source:
  fn: ImageHash-3.1.tar.gz
  url: https://pypi.python.org/packages/0c/1c/b6f539cc08cf8cfb12cb59a6883ee7f1cc0937cf3709247c2a15c8a1e665/ImageHash-3.1.tar.gz
  md5: 0bf909b6d138768f80dd689be7bedaaa

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - python
    - scipy
    - pillow
    - pywavelets
  run:
    - python
    - scipy
    - pillow
    - pywavelets

test:
  imports:
    - imagehash
