{% set version = "1.11.0" %}

package:
    name: iris
    version: {{ version }} 

source:
    git_url: https://github.com/SciTools/iris.git
    git_tag: v{{ version }}

build:
    number: 2
    skip: True  # [py35]

requirements:
    build:
        - python  # [not osx]
        - python >=2.7,<3  # [osx]
        - scipy
        - biggus >=0.14
        - cartopy >=0.14
        - netcdf4
        - numpy
        - udunits2
        - cf_units
        - pyke
        - setuptools
        - mo_pack  # [not win]
        - nc_time_axis
    run:
        - python  # [not osx]
        - python >=2.7,<3  # [osx]
        - scipy
        - biggus >=0.14
        - cartopy >=0.14
        - matplotlib
        - netcdf4
        - numpy
        - pyke
        - udunits2
        - cf_units
        - mo_pack  # [not win]
        - nc_time_axis
        - pep8
        - filelock
        - imagehash

test:
    imports:
        - iris
    commands:
        - python -c "import iris; print('version = {}'.format(iris.__version__))"

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: Analyse and visualise meteorological and oceanographic data sets.
