package:
    name: iris
    version: 1.10.0

source:
    git_url: https://github.com/SciTools/iris.git
    git_tag: v1.10.0

build:
    number: 2
    # See https://github.com/SciTools/cartopy/pull/676
    skip: True  # [py35]

requirements:
    build:
        - python  # [not osx]
        - python >=2.7,<3  # [osx]
        - scipy
        - biggus >=0.14
        - cartopy >=0.13
        - netcdf4
        - numpy x.x
        - udunits2
        - cf_units
        - pyke
        - setuptools
        - mo_pack  # [not win]
        - nc_time_axis
        - iris_grib  # [not win]
    run:
        - python  # [not osx]
        - python >=2.7,<3  # [osx]
        - scipy
        - biggus >=0.14
        - cartopy >=0.13
        - matplotlib
        - netcdf4
        - ecmwf_grib >=1.12.1  # [not win and not py3k]
        # There is a numpy C ABI dependency for as long as we have a C extension (pp_packing).
        - numpy x.x
        - pyke
        - udunits2
        - cf_units
        - mo_pack  # [not win]
        - nc_time_axis
        - iris_grib  # [not win]

test:
    imports:
        - iris
        - iris.fileformats.pp_packing  # [not win]

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: Analyse and visualise meteorological and oceanographic data sets.
