package:
    name: netcdf-fortran
    version: 4.4.3

source:
    git_url: https://github.com/Unidata/netcdf-fortran
    git_tag: v4.4.3

build:
    number: 1
    skip: True  # [win or osx]

requirements:
    build:
        - libnetcdf 4.2.1.1
        - krb5
    run:
        - libnetcdf 4.2.1.1
        - krb5

test:
    commands:
        - nf-config --all

about:
    home: https://github.com/Unidata/netcdf-fortran
    license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
    summary: Unidata NetCDF Fortran Library
