package:
    name: iris_sample_data
    version: "1.0.0.dev0"

source:
    fn: iris-sample-data-master.tar.gz
    url: http://github.com/SciTools/iris-sample-data/archive/master.tar.gz

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

build:
    script:
        - python setup.py install --single-version-externally-managed --record record.txt

test:
    imports:
        - iris_sample_data

about:
    home: http://scitools.org.uk/iris_sample_data
    license: Open Government
    summary: Iris sample data.