package:
    name: image-meta-tag
    version: "0.4.3"

source:
    git_url: https://github.com/SciTools-incubator/image-meta-tag
    git_tag: 0.4.3

build:
    number: 0

requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python >=2.7,<3
        - matplotlib
        - numpy
        - pillow

test:
    imports:
        - ImageMetaTag

about:
    license: BSD3
    summary: 'Image metadata tagging, database and presentation'
    home: https://github.com/SciTools-incubator/image-meta-tag
