{% set name = "olefile" %}
{% set version = "0.42.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 8a3226dba11349b51a2c6de6af0c889324201f14a8c30992b7877109090e36e0

build:
    number: 1
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - olefile
