{% set version = "0.15.0" %}
{% set sha256 = "fdee52cc2f259785a7744951ba43f339d33d517a5ec9cee301a33a267c60fd65" %}

package:
  name: cartopy
  version: {{ version }}

source:
  fn: cartopy-{{ version }}.tar.gz
  url: https://github.com/SciTools/cartopy/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cartopy.win.patch  # [win]

build:
  number: 0
  skip: True  # [py35 and win]

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy x.x
    - cython
    - proj.4
    - geos
    # On OSX We need to effectively pin the geos version to the
    # one used by the specific shapely being targetted (we're letting
    # conda's package solver will deal with that).
    - shapely >=1.5.6
    - owslib
    - pyshp
    - pyepsg
    - msinttypes  # [win]

  run:
    - python
    - six
    - mock
    - nose
    - pillow
    - owslib
    - numpy x.x
    - proj.4
    - shapely >=1.5.6
    - scipy
    - pyshp
    - matplotlib <2
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

