package:
  name: cartopy
  version: 0.14.2

source:
  fn: cartopy-0.14.2.tar.gz
  url: https://github.com/SciTools/cartopy/archive/v0.14.2.tar.gz
  sha256: 7ee4d38871b742cdde22f1982a10619bbe103c63575364988bd0be9c0ba57b6e
  patches:
    - cartopy.win.patch  # [win]

build:
  number: 0
  skip: True  # [py35 and win]

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy x.x
    - cython
    - proj.4
    - geos
    # On OSX We need to effectively pin the geos version to the
    # one used by the specific shapely being targetted (we're letting
    # conda's package solver will deal with that).
    - shapely >=1.5.6
    - owslib
    - pyshp
    - pyepsg
    - msinttypes  # [win]

  run:
    - python
    - six
    - mock
    - nose
    - pillow
    - owslib
    - numpy x.x
    - proj.4
    - shapely >=1.5.6
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

