package:
    name: nc_time_axis
    version: "1.0.0"

source:
    git_url: https://github.com/SciTools/nc-time-axis.git
    git_tag: v1.0.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six
        - matplotlib
        - netcdf4 >=1.1
        - numpy

test:
    imports:
        - nc_time_axis

about:
    license: BSD3
    summary: 'Support for netcdftime axis in matplotlib.'
