package:
    name: iris_grib
    version: "0.9.0"

source:
    git_url: https://github.com/SciTools/iris-grib.git
    git_tag: v0.9.0

build:
    skip: True  # [win or py3k]
    number: 2
    script:
        - python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - ecmwf_grib
    run:
        - python
        - ecmwf_grib

# test:
#     imports:
#         - iris_grib

about:
    home: http://scitools.org.uk/iris-grib
    license: LGPL
    summary: Iris GRIB interface
