package:
    name: iris_grib
    version: "0.9.0"

source:
    git_url: https://github.com/SciTools/iris-grib.git
    git_tag: v0.9.0

build:
    skip: True  # [win or py3k]
    number: 3
    script:
        - python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - ecmwf_grib
    run:
        - python
        - ecmwf_grib

test:
    requires:
        - iris
        - iris_sample_data
        - pep8
    commands:
        - python -m unittest discover -v iris_grib.tests

about:
    home: http://scitools.org.uk/iris-grib
    license: LGPL
    summary: Iris GRIB interface
